create table if not exists public.hp_tcg_cards (
  id bigint generated by default as identity primary key,
  card_no text unique,
  name_zh text not null,
  name_original text,
  name_jp text,
  name_en text,
  card_type text,
  house text,
  cost integer,
  rarity text,
  product text,
  image_url text,
  effect_zh text,
  effect_original text,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

alter table public.hp_tcg_cards enable row level security;

drop policy if exists "Allow public read hp tcg cards" on public.hp_tcg_cards;
create policy "Allow public read hp tcg cards"
on public.hp_tcg_cards
for select
to anon
using (true);

create table if not exists public.hp_tcg_visitor_logs (
  id bigint generated by default as identity primary key,
  visitor_id text,
  page_path text not null,
  page_title text,
  referrer text,
  user_agent text,
  screen_width integer,
  screen_height integer,
  created_at timestamp with time zone default now()
);

alter table public.hp_tcg_visitor_logs enable row level security;

drop policy if exists "Allow public insert hp tcg visitor logs" on public.hp_tcg_visitor_logs;
create policy "Allow public insert hp tcg visitor logs"
on public.hp_tcg_visitor_logs
for insert
to anon
with check (true);

drop policy if exists "Allow public read hp tcg visitor logs" on public.hp_tcg_visitor_logs;
create policy "Allow public read hp tcg visitor logs"
on public.hp_tcg_visitor_logs
for select
to anon
using (true);

insert into public.hp_tcg_cards (
  card_no, name_zh, name_original, card_type, house, cost, rarity, product, effect_zh, effect_original
) values
('HP-001', '哈利・波特', 'Harry Potter', '角色', '葛萊芬多', 5, 'R', '第一彈 起始系列', '登場時，可以查看牌庫上方 1 張牌。若該牌為咒語牌，可以加入手牌。', 'When this card enters play, look at the top card of your deck. If it is a spell card, add it to your hand.'),
('HP-002', '妙麗・格蘭傑', 'Hermione Granger', '角色', '葛萊芬多', 4, 'R', '第一彈 起始系列', '每回合 1 次，當你使用咒語牌時，抽 1 張牌，然後捨棄 1 張手牌。', 'Once per turn, when you play a spell card, draw 1 card, then discard 1 card.'),
('HP-003', '榮恩・衛斯理', 'Ron Weasley', '角色', '葛萊芬多', 3, 'N', '第一彈 起始系列', '若你的場上有「哈利・波特」，此卡獲得 +1 力量。', 'If you control Harry Potter, this card gains +1 power.')
on conflict (card_no) do nothing;
