import fs from "fs";
import path from "path";
import { chromium } from "playwright";

const ROOT_DIR = process.cwd();

const SRC_DATA_DIR = path.join(ROOT_DIR, "src", "data");
const CARD_QA_PATH = path.join(SRC_DATA_DIR, "cardQa.js");
const CARD_QA_DEBUG_PATH = path.join(SRC_DATA_DIR, "cardQaDebug.json");
const DETAIL_DEBUG_PATH = path.join(SRC_DATA_DIR, "officialCardDetailsDebug.json");

const OFFICIAL_CARDLIST_URL =
  "https://tcg.movic.jp/harrypotter/cardlist/?cardProductId=2";

const SEARCH_API =
  "https://tcg.movic.jp/harrypotter/card-management/api/public/cards/search";

const DETAIL_API =
  "https://tcg.movic.jp/harrypotter/card-management/api/public/cards/detail";

function ensureDir(dir) {
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }
}

function walkFiles(dir, files = []) {
  if (!fs.existsSync(dir)) return files;

  const items = fs.readdirSync(dir, { withFileTypes: true });

  for (const item of items) {
    const fullPath = path.join(dir, item.name);

    if (item.isDirectory()) {
      walkFiles(fullPath, files);
      continue;
    }

    if (
      item.isFile() &&
      (item.name.endsWith(".js") || item.name.endsWith(".json")) &&
      !item.name.includes("cardQa") &&
      !item.name.includes("Debug") &&
      !item.name.includes("official")
    ) {
      files.push(fullPath);
    }
  }

  return files;
}

function extractLocalCardNumbers() {
  const files = walkFiles(SRC_DATA_DIR);
  const cardNumbers = new Set();

  const cardNumberRegex = /\b(?:\d{2}|S\d{2}|PR)-\d{3}[a-z]?\b/g;

  for (const file of files) {
    const text = fs.readFileSync(file, "utf8");
    const matches = text.match(cardNumberRegex) || [];

    for (const match of matches) {
      cardNumbers.add(match);
    }
  }

  return [...cardNumbers].sort((a, b) =>
    a.localeCompare(b, "en", { numeric: true })
  );
}

function getBaseCardNumber(cardNumber = "") {
  return String(cardNumber).replace(/[a-z]$/i, "");
}

function safeText(value) {
  if (value === null || value === undefined) return "";
  return String(value).trim();
}

function getQaQuestion(qa = {}) {
  return (
    safeText(qa.question) ||
    safeText(qa.q) ||
    safeText(qa.questionText) ||
    safeText(qa.question_text) ||
    safeText(qa.body) ||
    safeText(qa.text)
  );
}

function getQaAnswer(qa = {}) {
  return (
    safeText(qa.answer) ||
    safeText(qa.a) ||
    safeText(qa.answerText) ||
    safeText(qa.answer_text) ||
    safeText(qa.response)
  );
}

function getQaUpdatedAt(qa = {}) {
  return (
    safeText(qa.updatedAt) ||
    safeText(qa.updated_at) ||
    safeText(qa.updateDate) ||
    safeText(qa.update_date) ||
    safeText(qa.publishedAt) ||
    safeText(qa.date)
  );
}

function normalizeQa(qa = {}) {
  return {
    id: qa.id ?? qa.qaId ?? qa.qa_id ?? "",
    question: getQaQuestion(qa),
    answer: getQaAnswer(qa),
    updatedAt: getQaUpdatedAt(qa),
    raw: qa
  };
}

function normalizeDetailToQaRecord(detail = {}) {
  const cardNumber = safeText(detail.cardNumber);
  const cardName = safeText(detail.cardName);
  const qas = Array.isArray(detail.qas) ? detail.qas : [];

  return {
    cardNumber,
    baseCardNumber: getBaseCardNumber(cardNumber),
    cardName,
    qas: qas
      .map(normalizeQa)
      .filter((qa) => qa.question || qa.answer || qa.id)
  };
}

function makeJsString(value) {
  return JSON.stringify(value, null, 2);
}

function buildCardQaJs(cardQaObject, meta) {
  return `// This file is auto-generated by scripts/downloadHarryPotterQa.js
// Do not edit manually.
// Generated at: ${meta.generatedAt}
// Detail API: ${DETAIL_API}

export const cardQa = ${makeJsString(cardQaObject)};

export function getBaseCardQaId(id = "") {
  return String(id || "").trim().replace(/[a-z]$/i, "");
}

export function getCardQa(card = {}) {
  if (!card) return [];

  const candidates = [
    card.cardNo,
    card.cardNumber,
    card.id,
    card.number,
    card.cardId
  ]
    .filter(Boolean)
    .map((value) => String(value).trim());

  for (const candidate of candidates) {
    if (cardQa[candidate]) {
      return cardQa[candidate];
    }

    const baseCandidate = getBaseCardQaId(candidate);

    if (cardQa[baseCandidate]) {
      return cardQa[baseCandidate];
    }
  }

  return [];
}

export default cardQa;
`;
}

async function postJsonInPage(page, url, payload) {
  return await page.evaluate(
    async ({ url, payload }) => {
      const response = await fetch(url, {
        method: "POST",
        headers: {
          "content-type": "application/json",
          accept: "application/json, text/plain, */*"
        },
        body: JSON.stringify(payload)
      });

      const text = await response.text();

      let data = null;

      try {
        data = JSON.parse(text);
      } catch {
        data = text;
      }

      return {
        ok: response.ok,
        status: response.status,
        url: response.url,
        data
      };
    },
    { url, payload }
  );
}

async function collectOfficialCardNumbers(page) {
  const cardNumbers = new Set();

  const payloads = [
    { cardProductId: 2 },
    { qaProductId: 2 },
    { productId: 2 },
    { cardProductIds: [2] },
    { products: [2] },
    {}
  ];

  for (const payload of payloads) {
    try {
      const result = await postJsonInPage(page, SEARCH_API, payload);

      if (!result.ok) continue;

      const data = result.data;

      if (!data || !Array.isArray(data.cards)) continue;

      for (const card of data.cards) {
        if (card.cardNumber) {
          cardNumbers.add(String(card.cardNumber).trim());
        }
      }
    } catch {
      // ignore failed payload
    }
  }

  return [...cardNumbers].sort((a, b) =>
    a.localeCompare(b, "en", { numeric: true })
  );
}

async function fetchCardDetail(page, cardNumber) {
  const result = await postJsonInPage(page, DETAIL_API, { cardNumber });

  if (!result.ok) {
    return {
      ok: false,
      cardNumber,
      status: result.status,
      error: `HTTP ${result.status}`,
      detail: null
    };
  }

  if (!result.data || typeof result.data !== "object") {
    return {
      ok: false,
      cardNumber,
      status: result.status,
      error: "Invalid JSON response",
      detail: null
    };
  }

  return {
    ok: true,
    cardNumber,
    status: result.status,
    error: "",
    detail: result.data
  };
}

async function main() {
  ensureDir(SRC_DATA_DIR);

  console.log("Opening official Card List page...");
  console.log(OFFICIAL_CARDLIST_URL);

  const browser = await chromium.launch({
    headless: true
  });

  const page = await browser.newPage({
    viewport: {
      width: 1440,
      height: 1000
    }
  });

  await page.goto(OFFICIAL_CARDLIST_URL, {
    waitUntil: "networkidle",
    timeout: 60000
  });

  console.log("");
  console.log("Collecting card numbers...");

  const localCardNumbers = extractLocalCardNumbers();
  const officialCardNumbers = await collectOfficialCardNumbers(page);

  const allCardNumbers = [
    ...new Set([...localCardNumbers, ...officialCardNumbers])
  ].sort((a, b) => a.localeCompare(b, "en", { numeric: true }));

  console.log(`Local card numbers: ${localCardNumbers.length}`);
  console.log(`Official card numbers: ${officialCardNumbers.length}`);
  console.log(`Total unique card numbers: ${allCardNumbers.length}`);
  console.log("");

  const cardQaObject = {};
  const debugRecords = [];
  const detailDebugRecords = [];

  let successCount = 0;
  let qaCardCount = 0;
  let qaRecordCount = 0;
  let failCount = 0;

  for (let i = 0; i < allCardNumbers.length; i++) {
    const cardNumber = allCardNumbers[i];

    process.stdout.write(
      `Fetching detail ${i + 1}/${allCardNumbers.length}: ${cardNumber} ... `
    );

    try {
      const result = await fetchCardDetail(page, cardNumber);

      detailDebugRecords.push(result);

      if (!result.ok) {
        failCount++;
        console.log(`failed (${result.error})`);
        continue;
      }

      successCount++;

      const record = normalizeDetailToQaRecord(result.detail);

      debugRecords.push(record);

      if (record.qas.length > 0) {
        qaCardCount++;
        qaRecordCount += record.qas.length;

        cardQaObject[record.cardNumber] = record.qas;

        const baseCardNumber = record.baseCardNumber;

        if (baseCardNumber && baseCardNumber !== record.cardNumber) {
          if (!cardQaObject[baseCardNumber]) {
            cardQaObject[baseCardNumber] = record.qas;
          }
        }

        console.log(`Q&A found: ${record.qas.length}`);
      } else {
        console.log("no Q&A");
      }

      await page.waitForTimeout(120);
    } catch (error) {
      failCount++;

      detailDebugRecords.push({
        ok: false,
        cardNumber,
        status: "",
        error: error.message,
        detail: null
      });

      console.log(`error: ${error.message}`);
    }
  }

  const meta = {
    generatedAt: new Date().toISOString(),
    officialCardlistUrl: OFFICIAL_CARDLIST_URL,
    searchApi: SEARCH_API,
    detailApi: DETAIL_API,
    localCardNumbersCount: localCardNumbers.length,
    officialCardNumbersCount: officialCardNumbers.length,
    totalUniqueCardNumbers: allCardNumbers.length,
    successCount,
    failCount,
    qaCardCount,
    qaRecordCount
  };

  const cardQaJs = buildCardQaJs(cardQaObject, meta);

  fs.writeFileSync(CARD_QA_PATH, cardQaJs, "utf8");

  fs.writeFileSync(
    CARD_QA_DEBUG_PATH,
    JSON.stringify(
      {
        meta,
        cardQa: cardQaObject,
        records: debugRecords
      },
      null,
      2
    ),
    "utf8"
  );

  fs.writeFileSync(
    DETAIL_DEBUG_PATH,
    JSON.stringify(
      {
        meta,
        details: detailDebugRecords
      },
      null,
      2
    ),
    "utf8"
  );

  await browser.close();

  console.log("");
  console.log("Done.");
  console.log(`Success detail requests: ${successCount}`);
  console.log(`Failed detail requests: ${failCount}`);
  console.log(`Cards with Q&A: ${qaCardCount}`);
  console.log(`Total Q&A records: ${qaRecordCount}`);
  console.log("");
  console.log("Saved:");
  console.log(CARD_QA_PATH);
  console.log(CARD_QA_DEBUG_PATH);
  console.log(DETAIL_DEBUG_PATH);
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});