import fs from "fs";
import path from "path";
import { pathToFileURL } from "url";

const ROOT_DIR = process.cwd();

const CARD_QA_PATH = path.join(ROOT_DIR, "src", "data", "cardQa.js");
const CARD_QA_DEBUG_PATH = path.join(ROOT_DIR, "src", "data", "cardQaDebug.json");

function safeText(value) {
  if (value === null || value === undefined) return "";
  return String(value).trim();
}

function sortCardNumbers(a, b) {
  return a.localeCompare(b, "en", { numeric: true });
}

function makeTranslationKey(qa = {}) {
  const id = safeText(qa.id);

  if (id) {
    return `id:${id}`;
  }

  const question =
    safeText(qa.originalQuestion) ||
    safeText(qa.raw?.question) ||
    safeText(qa.question);

  return `q:${question}`;
}

function normalizeOfficialQa(qa = {}) {
  return {
    id: qa.id ?? "",
    question: safeText(qa.question),
    answer: safeText(qa.answer),
    updatedAt: safeText(qa.updatedAt),
    raw: qa.raw || qa
  };
}

function buildTranslationMap(currentCardQa = {}) {
  const map = new Map();

  for (const qas of Object.values(currentCardQa)) {
    if (!Array.isArray(qas)) continue;

    for (const qa of qas) {
      const key = makeTranslationKey(qa);

      if (!key) continue;

      map.set(key, {
        id: qa.id ?? "",
        question: safeText(qa.question),
        answer: safeText(qa.answer),
        updatedAt: safeText(qa.updatedAt),
        originalQuestion:
          safeText(qa.originalQuestion) ||
          safeText(qa.raw?.question) ||
          safeText(qa.question),
        originalAnswer:
          safeText(qa.originalAnswer) ||
          safeText(qa.raw?.answer) ||
          safeText(qa.answer),
        raw: qa.raw || qa
      });
    }
  }

  return map;
}

function buildFixedQaRecord(officialQa, translationMap) {
  const normalizedOfficial = normalizeOfficialQa(officialQa);
  const key = makeTranslationKey(normalizedOfficial);
  const translated = translationMap.get(key);

  if (translated) {
    return {
      id: normalizedOfficial.id,
      question: translated.question || normalizedOfficial.question,
      answer: translated.answer || normalizedOfficial.answer,
      updatedAt: normalizedOfficial.updatedAt || translated.updatedAt || "",
      originalQuestion: normalizedOfficial.question,
      originalAnswer: normalizedOfficial.answer,
      raw: normalizedOfficial.raw
    };
  }

  return {
    id: normalizedOfficial.id,
    question: normalizedOfficial.question,
    answer: normalizedOfficial.answer,
    updatedAt: normalizedOfficial.updatedAt,
    originalQuestion: normalizedOfficial.question,
    originalAnswer: normalizedOfficial.answer,
    raw: normalizedOfficial.raw
  };
}

function buildCardQaJs(cardQaObject) {
  return `// This file is auto-generated by scripts/fixCardQaMapping.js
// Mapping rule: trust official cards/detail cardNumber, not mentioned card numbers inside Q&A text.
// Do not edit manually.
// Generated at: ${new Date().toISOString()}

export const cardQa = ${JSON.stringify(cardQaObject, null, 2)};

export function getBaseCardQaId(id = "") {
  return String(id || "").trim().replace(/[a-z]$/i, "");
}

export function getCardQa(card = {}) {
  if (!card) return [];

  const candidates = [
    card.cardNo,
    card.cardNumber,
    card.id,
    card.number,
    card.cardId
  ]
    .filter(Boolean)
    .map((value) => String(value).trim());

  for (const candidate of candidates) {
    if (cardQa[candidate]) {
      return cardQa[candidate];
    }

    const baseCandidate = getBaseCardQaId(candidate);

    if (cardQa[baseCandidate]) {
      return cardQa[baseCandidate];
    }
  }

  return [];
}

export default cardQa;
`;
}

async function main() {
  if (!fs.existsSync(CARD_QA_DEBUG_PATH)) {
    console.error("找不到 src/data/cardQaDebug.json，請先執行 npm run download:qa");
    process.exit(1);
  }

  if (!fs.existsSync(CARD_QA_PATH)) {
    console.error("找不到 src/data/cardQa.js，請先執行 npm run translate:qa");
    process.exit(1);
  }

  const currentModuleUrl = `${pathToFileURL(CARD_QA_PATH).href}?t=${Date.now()}`;
  const currentModule = await import(currentModuleUrl);
  const currentCardQa = currentModule.cardQa || {};

  const debugData = JSON.parse(fs.readFileSync(CARD_QA_DEBUG_PATH, "utf8"));
  const officialCardQa = debugData.cardQa || {};

  const translationMap = buildTranslationMap(currentCardQa);

  const fixedCardQa = {};

  let officialCardKeyCount = 0;
  let officialQaCount = 0;
  let translatedCount = 0;
  let fallbackCount = 0;

  const sortedOfficialCardNumbers = Object.keys(officialCardQa).sort(sortCardNumbers);

  for (const cardNumber of sortedOfficialCardNumbers) {
    const qas = officialCardQa[cardNumber];

    if (!Array.isArray(qas) || qas.length === 0) continue;

    officialCardKeyCount++;

    fixedCardQa[cardNumber] = qas.map((officialQa) => {
      officialQaCount++;

      const key = makeTranslationKey(officialQa);
      const hasTranslation = translationMap.has(key);

      if (hasTranslation) {
        translatedCount++;
      } else {
        fallbackCount++;
      }

      return buildFixedQaRecord(officialQa, translationMap);
    });
  }

  const sortedFixedCardQa = {};

  for (const cardNumber of Object.keys(fixedCardQa).sort(sortCardNumbers)) {
    sortedFixedCardQa[cardNumber] = fixedCardQa[cardNumber];
  }

  fs.writeFileSync(CARD_QA_PATH, buildCardQaJs(sortedFixedCardQa), "utf8");

  console.log("Card Q&A mapping restored by official detail cardNumber.");
  console.log(`Official card keys with Q&A: ${officialCardKeyCount}`);
  console.log(`Official Q&A mappings: ${officialQaCount}`);
  console.log(`Chinese translations reused: ${translatedCount}`);
  console.log(`Fallback original Japanese records: ${fallbackCount}`);
  console.log(`Saved: ${CARD_QA_PATH}`);
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});